export const SPOTLIGHT_10 = [
  {
    rank: 1,
    name: "Xeris",
    location: "United States",
    founded: 2023,
    employees: "11-50",
    desc: "The world's first hardware-secured triple consensus blockchain (PoW + PoS + PoH) optimized for high-frequency institutional RWA settlements. Xeris delivers unlimited liquidity and 10,000 TPS with immutable cryptographic proof — engineering the global standard for digital value exchange.",
    tags: ["Blockchain Infrastructure", "RWA", "Institutional", "L1"],
    url: "https://xerisweb.com/",
    highlight: "⭐ SPONSORED · Triple Consensus L1 · 10,000 TPS",
    sponsored: true,
  },
  {
    rank: 2,
    name: "Zera Labs",
    location: "United States",
    founded: 2024,
    employees: "11-50",
    desc: "Pioneering the new era of digital cash with zero-knowledge privacy. Zera turns crypto assets into private, portable, and secure digital cash via a unified ZK pool — enabling shielded balances, offline P2P payments, and seamless DeFi hooks built on Solana.",
    tags: ["Identity & Security", "DeFi", "ZK Proofs", "Privacy"],
    url: "https://zeralabs.org/",
    highlight: "⭐ SPONSORED · Zero-Knowledge · Offline P2P",
    sponsored: true,
  },
  {
    rank: 3,
    name: "Solana",
    location: "United States",
    founded: 2020,
    employees: "100-500",
    desc: "The world's highest-performance Layer 1 blockchain — 65,000 TPS, sub-second finality, and near-zero fees. Solana powers the fastest-growing ecosystem in DeFi, NFTs, payments, and consumer crypto apps.",
    tags: ["Blockchain Infrastructure", "Layer 1", "DeFi", "High Performance"],
    url: "https://solana.com/",
    highlight: "⭐ SPONSORED · 65,000 TPS · Sub-Second Finality",
    sponsored: true,
  },
  {
    rank: 4,
    name: "Streamflow",
    location: "United States",
    founded: 2021,
    employees: "11-50",
    desc: "The leading token distribution and staking infrastructure on Solana. Streamflow powers vesting, payroll, staking pools, and multi-recipient token streams — trusted by hundreds of Web3 projects for secure, automated on-chain payments.",
    tags: ["DeFi", "Staking", "Token Vesting", "Payments"],
    url: "https://streamflow.finance/staking",
    highlight: "⭐ SPONSORED · Staking · Token Vesting",
    sponsored: true,
  },
  {
    rank: 5,
    name: "Phantom",
    location: "United States",
    founded: 2021,
    employees: "11-50",
    desc: "The #1 crypto wallet for Solana and multi-chain. Phantom makes it safe and easy to store, buy, send, receive, swap tokens, and collect NFTs across Solana, Ethereum, Bitcoin, Polygon, and Base.",
    tags: ["Wallet", "DeFi", "NFT", "Multi-Chain"],
    url: "https://phantom.com/",
    highlight: "⭐ SPONSORED · #1 Solana Wallet · Multi-Chain",
    sponsored: true,
  },
  {
    rank: 6,
    name: "Jupiter",
    location: "United States",
    founded: 2021,
    employees: "11-50",
    desc: "The #1 liquidity aggregator and swap infrastructure on Solana. Jupiter routes trades across all major DEXs to guarantee the best price, and powers limit orders, DCA, and perpetuals for the Solana ecosystem.",
    tags: ["DeFi", "DEX Aggregator", "Solana", "Liquidity"],
    url: "https://jup.ag/",
    highlight: "⭐ SPONSORED · #1 Solana DEX Aggregator",
    sponsored: true,
  },
  {
    rank: 7,
    name: "Pump.fun",
    location: "United States",
    founded: 2024,
    employees: "11-50",
    desc: "The leading token launch platform on Solana. Pump.fun enables anyone to create and launch fair-launch memecoins in seconds with a built-in bonding curve and instant liquidity — the most-used launchpad in crypto history.",
    tags: ["DeFi", "Token Launch", "Solana", "Memecoins"],
    url: "https://pump.fun/",
    highlight: "⭐ SPONSORED · #1 Token Launchpad · Solana",
    sponsored: true,
  },
  {
    rank: 8,
    name: "Coinbase",
    location: "San Francisco, CA",
    founded: 2012,
    employees: "5000+",
    desc: "America's largest publicly-traded cryptocurrency exchange and wallet provider. Listed on NASDAQ (COIN), Coinbase serves over 100 million verified users across 100+ countries with trading, staking, custody, and institutional services.",
    tags: ["Exchange", "Custody", "Institutional", "Wallet"],
    url: "https://www.coinbase.com/",
    highlight: "NASDAQ Listed · 100M+ Users",
  },
  {
    rank: 9,
    name: "Ripple",
    location: "San Francisco, CA",
    founded: 2012,
    employees: "500-1000",
    desc: "Enterprise blockchain company enabling real-time global payments via the XRP Ledger. Ripple's On-Demand Liquidity (ODL) solution is used by hundreds of financial institutions to move value across borders instantly.",
    tags: ["Payments", "Blockchain", "XRP", "Enterprise"],
    url: "https://ripple.com/",
    highlight: "XRP Ledger · Global Payments",
  },
  {
    rank: 10,
    name: "Kraken",
    location: "San Francisco, CA",
    founded: 2011,
    employees: "1000-5000",
    desc: "One of the world's oldest and most trusted cryptocurrency exchanges, offering spot trading, futures, staking, and institutional services. Kraken Pro is favored by professional traders for its depth of liquidity.",
    tags: ["Exchange", "Futures", "Staking", "Pro Trading"],
    url: "https://www.kraken.com/",
    highlight: "Founded 2011 · Most Trusted",
  },
  {
    rank: 10,
    name: "Gemini",
    location: "New York, NY",
    founded: 2014,
    employees: "500-1000",
    desc: "Founded by Tyler and Cameron Winklevoss, Gemini is a regulated crypto exchange and custodian. First exchange licensed by New York DFS, pioneering SOC 2 Type 2 certification and regulatory compliance in crypto.",
    tags: ["Exchange", "Custody", "Regulated", "NFT"],
    url: "https://www.gemini.com/",
    highlight: "NYDFS Licensed · SOC 2 Certified",
  },
  {
    rank: 10,
    name: "Chainalysis",
    location: "New York, NY",
    founded: 2014,
    employees: "500-1000",
    desc: "The world's leading blockchain analytics and compliance platform. Chainalysis tools are used by the IRS, FBI, and over 70 governments worldwide to investigate crypto crime, fraud, and sanctions evasion.",
    tags: ["Analytics", "Compliance", "Government", "Forensics"],
    url: "https://www.chainalysis.com/",
    highlight: "FBI & IRS Partner · 70+ Governments",
  },
  {
    rank: 9,
    name: "Paxos",
    location: "New York, NY",
    founded: 2012,
    employees: "100-500",
    desc: "Regulated blockchain infrastructure company that tokenizes and settles assets on behalf of enterprise clients. Issues USDP stablecoin and powers PayPal USD (PYUSD). Holds OCC Trust Company charter.",
    tags: ["Stablecoin", "Settlement", "Tokenization", "Enterprise"],
    url: "https://paxos.com/",
    highlight: "OCC Trust Charter · PYUSD Issuer",
  },
  {
    rank: 10,
    name: "Circle",
    location: "Boston, MA",
    founded: 2013,
    employees: "500-1000",
    desc: "Creator of USDC, the world's second-largest stablecoin with over $40 billion in circulation. Circle's programmable dollar infrastructure powers fintech apps, DeFi protocols, and cross-border payments globally.",
    tags: ["Stablecoin", "USDC", "Payments", "DeFi"],
    url: "https://www.circle.com/",
    highlight: "USDC · $40B+ Circulation",
  },
  {
    rank: 8,
    name: "Anchorage Digital",
    location: "San Francisco, CA",
    founded: 2017,
    employees: "100-500",
    desc: "First federally chartered crypto bank in the US, holding an OCC National Trust Bank charter. Provides institutional-grade custody, staking, trading, and financing for the largest financial institutions.",
    tags: ["Custody", "Banking", "Institutional", "Staking"],
    url: "https://www.anchorage.com/",
    highlight: "First US Crypto National Bank",
  },
  {
    rank: 9,
    name: "Lightning Labs",
    location: "San Francisco, CA",
    founded: 2016,
    employees: "11-50",
    desc: "Core developer of the Lightning Network — Bitcoin's Layer 2 payment protocol enabling near-instant, near-zero-fee transactions at scale. Their LND implementation powers millions of Bitcoin payment channels worldwide.",
    tags: ["Bitcoin", "Layer 2", "Payments", "Lightning Network"],
    url: "https://lightning.engineering/",
    highlight: "Lightning Network · Bitcoin L2",
  },
  {
    rank: 10,
    name: "Alchemy",
    location: "San Francisco, CA",
    founded: 2017,
    employees: "100-500",
    desc: "The leading Web3 developer platform powering over $105 billion in transactions. Alchemy's APIs and infrastructure underpin major DeFi, NFT, and blockchain applications including OpenSea, Aave, and Uniswap.",
    tags: ["Web3", "Developer Tools", "API", "Infrastructure"],
    url: "https://www.alchemy.com/",
    highlight: "$105B+ Transactions Powered",
  },
];

export const ALL_100_DIGITAL = [
  // Sponsored
  { name: "Pump.fun", category: "DeFi", location: "United States", founded: 2024, desc: "The leading token launch platform on Solana. Create and launch fair-launch memecoins in seconds with a built-in bonding curve and instant liquidity.", url: "https://pump.fun/", sponsored: true },
  { name: "Jupiter", category: "DeFi", location: "United States", founded: 2021, desc: "The #1 liquidity aggregator and swap infrastructure on Solana. Routes trades across all major DEXs for the best price, plus limit orders, DCA, and perpetuals.", url: "https://jup.ag/", sponsored: true },
  { name: "Solana", category: "Blockchain Infrastructure", location: "United States", founded: 2020, desc: "The world's highest-performance Layer 1 blockchain — 65,000 TPS, sub-second finality, and near-zero fees powering the fastest-growing DeFi and NFT ecosystem.", url: "https://solana.com/", sponsored: true },
  { name: "Streamflow", category: "DeFi", location: "United States", founded: 2021, desc: "Leading token distribution and staking infrastructure on Solana. Powers vesting, payroll, staking pools, and multi-recipient token streams for hundreds of Web3 projects.", url: "https://streamflow.finance/staking", sponsored: true },
  { name: "Phantom", category: "Identity & Security", location: "United States", founded: 2021, desc: "The #1 crypto wallet for Solana and multi-chain. Store, buy, send, swap tokens, and collect NFTs across Solana, Ethereum, Bitcoin, Polygon, and Base.", url: "https://phantom.com/", sponsored: true },
  { name: "Xeris", category: "Blockchain Infrastructure", location: "United States", founded: 2023, desc: "The world's first hardware-secured triple consensus blockchain (PoW + PoS + PoH) optimized for high-frequency institutional RWA settlements. Delivers unlimited liquidity and 10,000 TPS with immutable cryptographic proof.", url: "https://xerisweb.com/", sponsored: true },
  { name: "Zera Labs", category: "Identity & Security", location: "United States", founded: 2024, desc: "Pioneering the new era of digital cash with zero-knowledge privacy. Turns crypto assets into private, portable, and secure digital cash via a unified ZK pool — enabling shielded balances, offline P2P payments, and seamless DeFi hooks built on Solana.", url: "https://zeralabs.org/", sponsored: true },
  // Exchanges
  { name: "Coinbase", category: "Exchange", location: "San Francisco, CA", founded: 2012, desc: "America's largest regulated crypto exchange, publicly listed on NASDAQ. Serving 100M+ users.", url: "https://www.coinbase.com/" },
  { name: "Kraken", category: "Exchange", location: "San Francisco, CA", founded: 2011, desc: "One of the world's oldest crypto exchanges offering spot, futures, staking, and OTC trading.", url: "https://www.kraken.com/" },
  { name: "Gemini", category: "Exchange", location: "New York, NY", founded: 2014, desc: "NYDFS-regulated exchange and custodian founded by the Winklevoss twins.", url: "https://www.gemini.com/" },
  { name: "Binance.US", category: "Exchange", location: "Wilmington, DE", founded: 2019, desc: "US-compliant version of Binance, one of the world's largest crypto trading platforms.", url: "https://www.binance.us/" },
  { name: "Bittrex", category: "Exchange", location: "Seattle, WA", founded: 2014, desc: "US-based crypto exchange known for wide altcoin selection and security focus.", url: "https://bittrex.com/" },
  { name: "CEX.IO", category: "Exchange", location: "Chicago, IL", founded: 2013, desc: "Multi-functional crypto exchange offering buy/sell, staking, and yield earning services.", url: "https://cex.io/" },
  { name: "Bitstamp", category: "Exchange", location: "New York, NY", founded: 2011, desc: "One of the longest-running crypto exchanges with institutional-grade liquidity.", url: "https://www.bitstamp.net/" },
  { name: "Lightspeed Crypto", category: "Exchange", location: "Lambertville, NJ", founded: 2021, desc: "Advanced crypto trading platform with no added fees, offering Bitcoin, Ethereum and more.", url: "https://lightspeedcrypto.com/" },
  { name: "Crypxie Exchange", category: "Exchange", location: "United States", founded: 2020, desc: "Global digital assets exchange with experienced blockchain team and low commissions.", url: "https://crypxie.com/" },
  { name: "Coin Cloud", category: "Exchange", location: "Las Vegas, NV", founded: 2014, desc: "World's leading Crypto ATM company with 5,000+ Digital Currency Machines in the USA.", url: "https://www.coincloud.com/" },
  // Blockchain Infrastructure
  { name: "Ripple", category: "Blockchain Infrastructure", location: "San Francisco, CA", founded: 2012, desc: "Enterprise blockchain enabling real-time global payments via XRP Ledger.", url: "https://ripple.com/" },
  { name: "Circle", category: "Stablecoin & Payments", location: "Boston, MA", founded: 2013, desc: "Creator of USDC stablecoin with $40B+ in circulation powering DeFi and payments.", url: "https://www.circle.com/" },
  { name: "Paxos", category: "Stablecoin & Payments", location: "New York, NY", founded: 2012, desc: "Regulated blockchain infrastructure issuing USDP and PYUSD stablecoins.", url: "https://paxos.com/" },
  { name: "Alchemy", category: "Developer Tools", location: "San Francisco, CA", founded: 2017, desc: "Leading Web3 developer platform powering $105B+ in transactions for top DeFi apps.", url: "https://www.alchemy.com/" },
  { name: "Anchorage Digital", category: "Custody & Banking", location: "San Francisco, CA", founded: 2017, desc: "First federally chartered crypto bank in the US with OCC National Trust charter.", url: "https://www.anchorage.com/" },
  { name: "Lightning Labs", category: "Blockchain Infrastructure", location: "San Francisco, CA", founded: 2016, desc: "Core developer of Bitcoin's Lightning Network Layer 2 payment protocol.", url: "https://lightning.engineering/" },
  { name: "Chainalysis", category: "Analytics & Compliance", location: "New York, NY", founded: 2014, desc: "Blockchain analytics platform used by IRS, FBI, and 70+ governments worldwide.", url: "https://www.chainalysis.com/" },
  { name: "HashCash Consultants", category: "Blockchain Infrastructure", location: "Palo Alto, CA", founded: 2015, desc: "Blockchain company enabling cross-border payments with 100+ clients in 26 countries.", url: "https://www.hashcashconsultants.com/" },
  { name: "Paradigm", category: "Venture Capital", location: "San Francisco, CA", founded: 2018, desc: "Leading crypto-focused investment firm backing foundational blockchain protocols.", url: "https://paradigm.xyz/" },
  { name: "CoinDesk", category: "Media & Data", location: "New York, NY", founded: 2013, desc: "Premier crypto media company and data provider for institutional and retail investors.", url: "https://www.coindesk.com/" },
  // DeFi & Web3
  { name: "Uniswap Labs", category: "DeFi", location: "New York, NY", founded: 2018, desc: "Creator of Uniswap, the world's largest decentralized exchange protocol by volume.", url: "https://uniswap.org/" },
  { name: "Aave", category: "DeFi", location: "United States", founded: 2017, desc: "Leading DeFi lending and borrowing protocol with billions in total value locked.", url: "https://aave.com/" },
  { name: "Compound Finance", category: "DeFi", location: "San Francisco, CA", founded: 2018, desc: "Algorithmic money market protocol on Ethereum enabling crypto lending and borrowing.", url: "https://compound.finance/" },
  { name: "dYdX", category: "DeFi", location: "San Francisco, CA", founded: 2017, desc: "Decentralized perpetuals exchange offering derivatives trading without a centralized order book.", url: "https://dydx.exchange/" },
  { name: "0x Labs", category: "DeFi", location: "San Francisco, CA", founded: 2017, desc: "Decentralized exchange infrastructure powering token swaps across major DeFi protocols.", url: "https://0x.org/" },
  { name: "Opyn", category: "DeFi", location: "San Francisco, CA", founded: 2019, desc: "Decentralized options protocol enabling permissionless hedging and DeFi derivatives.", url: "https://www.opyn.co/" },
  { name: "Balancer Labs", category: "DeFi", location: "United States", founded: 2018, desc: "Automated portfolio manager and decentralized trading protocol on Ethereum.", url: "https://balancer.fi/" },
  { name: "Synthetix", category: "DeFi", location: "United States", founded: 2017, desc: "Decentralized synthetic asset issuance protocol enabling exposure to real-world assets.", url: "https://synthetix.io/" },
  { name: "Dharma", category: "DeFi", location: "San Francisco, CA", founded: 2017, desc: "DeFi savings and investment app making decentralized finance accessible to retail users.", url: "https://dharma.io/" },
  { name: "Ribbon Finance", category: "DeFi", location: "United States", founded: 2021, desc: "DeFi structured products protocol offering automated options strategies for yield generation.", url: "https://www.ribbon.finance/" },
  // NFT & Gaming
  { name: "OpenSea", category: "NFT & Marketplace", location: "New York, NY", founded: 2017, desc: "The world's largest NFT marketplace with billions in secondary sales volume.", url: "https://opensea.io/" },
  { name: "Dapper Labs", category: "NFT & Gaming", location: "United States", founded: 2018, desc: "Creator of NBA Top Shot and Flow blockchain, bringing NFTs to mainstream sports fans.", url: "https://www.dapperlabs.com/" },
  { name: "Axie Infinity (Sky Mavis US)", category: "NFT & Gaming", location: "United States", founded: 2018, desc: "Pioneering play-to-earn blockchain game with NFT creatures driving a digital economy.", url: "https://axieinfinity.com/" },
  { name: "Sorare", category: "NFT & Gaming", location: "New York, NY", founded: 2018, desc: "Fantasy sports platform using NFT player cards licensed from top football clubs.", url: "https://sorare.com/" },
  { name: "Rarible", category: "NFT & Marketplace", location: "United States", founded: 2020, desc: "Community-owned NFT marketplace with RARI governance token and creator royalties.", url: "https://rarible.com/" },
  { name: "SuperRare", category: "NFT & Marketplace", location: "New York, NY", founded: 2018, desc: "Curated NFT art marketplace focused on single-edition digital artwork by top creators.", url: "https://superrare.com/" },
  { name: "Nifty Gateway", category: "NFT & Marketplace", location: "New York, NY", founded: 2018, desc: "Premium NFT drop platform backed by Gemini, hosting exclusive artist collaborations.", url: "https://www.niftygateway.com/" },
  { name: "Yuga Labs", category: "NFT & Gaming", location: "Miami, FL", founded: 2021, desc: "Creator of Bored Ape Yacht Club, CryptoPunks, and the Otherside metaverse.", url: "https://yuga.com/" },
  { name: "Immutable", category: "NFT & Gaming", location: "United States", founded: 2018, desc: "Layer 2 blockchain scaling solution purpose-built for NFT gaming with zero gas fees.", url: "https://www.immutable.com/" },
  { name: "Sandbox", category: "NFT & Gaming", location: "United States", founded: 2012, desc: "Decentralized gaming metaverse where players build, own, and monetize virtual experiences.", url: "https://www.sandbox.game/" },
  // Custody & Institutional
  { name: "BitGo", category: "Custody & Banking", location: "Palo Alto, CA", founded: 2013, desc: "Institutional digital asset custody and security, processing $20B+ in monthly transactions.", url: "https://www.bitgo.com/" },
  { name: "Fidelity Digital Assets", category: "Custody & Banking", location: "Boston, MA", founded: 2018, desc: "Fidelity's crypto custody and trading arm for institutional investors managing digital assets.", url: "https://www.fidelitydigitalassets.com/" },
  { name: "Galaxy Digital", category: "Custody & Banking", location: "New York, NY", founded: 2018, desc: "Diversified financial services and investment management firm for the digital asset economy.", url: "https://www.galaxy.com/" },
  { name: "Prime Trust", category: "Custody & Banking", location: "Las Vegas, NV", founded: 2016, desc: "Crypto banking and trust infrastructure for exchanges, wallets, and broker-dealers.", url: "https://www.primetrust.com/" },
  { name: "Bakkt", category: "Custody & Banking", location: "Alpharetta, GA", founded: 2018, desc: "Institutional-grade Bitcoin futures and custody platform backed by NYSE parent ICE.", url: "https://www.bakkt.com/" },
  { name: "Copper", category: "Custody & Banking", location: "New York, NY", founded: 2018, desc: "Institutional crypto custody, prime brokerage, and settlement infrastructure.", url: "https://copper.co/" },
  { name: "Knox Custody", category: "Custody & Banking", location: "United States", founded: 2019, desc: "Regulated crypto asset custody for institutional clients with multi-signature security.", url: "https://knoxcustody.com/" },
  { name: "Fireblocks", category: "Custody & Banking", location: "New York, NY", founded: 2018, desc: "Digital asset custody and transfer network securing $4T+ in assets for 1,800+ institutions.", url: "https://www.fireblocks.com/" },
  // Analytics & Compliance
  { name: "CipherTrace", category: "Analytics & Compliance", location: "Menlo Park, CA", founded: 2015, desc: "Crypto AML and blockchain analytics platform acquired by Mastercard.", url: "https://ciphertrace.com/" },
  { name: "Elliptic", category: "Analytics & Compliance", location: "New York, NY", founded: 2013, desc: "Blockchain analytics for crypto AML compliance used by major exchanges and regulators.", url: "https://www.elliptic.co/" },
  { name: "TRM Labs", category: "Analytics & Compliance", location: "San Francisco, CA", founded: 2018, desc: "Blockchain intelligence platform helping financial institutions fight crypto crime.", url: "https://www.trmlabs.com/" },
  { name: "Crypto Currency Services", category: "Analytics & Compliance", location: "Los Angeles, CA", founded: 2015, desc: "Blockchain consulting and ICO advisory specializing in financial inclusion solutions.", url: "https://www.cryptocurrencyservices.com/" },
  // Developer Tools & Infrastructure
  { name: "Infura", category: "Developer Tools", location: "New York, NY", founded: 2016, desc: "Ethereum and IPFS API provider serving the backbone of Web3 development infrastructure.", url: "https://infura.io/" },
  { name: "Moralis", category: "Developer Tools", location: "United States", founded: 2021, desc: "Web3 backend infrastructure platform enabling rapid blockchain app development.", url: "https://moralis.io/" },
  { name: "Thirdweb", category: "Developer Tools", location: "San Francisco, CA", founded: 2021, desc: "Web3 development framework enabling smart contract deployment with no-code tools.", url: "https://thirdweb.com/" },
  { name: "Hardhat", category: "Developer Tools", location: "United States", founded: 2019, desc: "Ethereum development environment for building, testing, and deploying smart contracts.", url: "https://hardhat.org/" },
  { name: "QuickNode", category: "Developer Tools", location: "Miami, FL", founded: 2017, desc: "Blazing-fast blockchain node infrastructure for Web3 developers across 20+ chains.", url: "https://www.quicknode.com/" },
  { name: "Tenderly", category: "Developer Tools", location: "United States", founded: 2018, desc: "Smart contract monitoring, debugging, and simulation platform for Ethereum developers.", url: "https://tenderly.co/" },
  { name: "The Graph", category: "Developer Tools", location: "San Francisco, CA", founded: 2018, desc: "Decentralized indexing protocol for querying blockchain data, used by top DeFi apps.", url: "https://thegraph.com/" },
  { name: "Gelato Network", category: "Developer Tools", location: "United States", founded: 2020, desc: "Smart contract automation platform enabling recurring on-chain execution on Ethereum.", url: "https://www.gelato.network/" },
  // Payments & Fintech
  { name: "BitPay", category: "Payments", location: "Atlanta, GA", founded: 2011, desc: "Oldest and largest Bitcoin payment processor, enabling merchants to accept crypto globally.", url: "https://bitpay.com/" },
  { name: "Flexa", category: "Payments", location: "New York, NY", founded: 2018, desc: "Instant crypto payments network enabling digital currency spending at major retailers.", url: "https://flexa.co/" },
  { name: "Wyre", category: "Payments", location: "San Francisco, CA", founded: 2013, desc: "Crypto on/off ramp and payment infrastructure for fintech apps and exchanges.", url: "https://www.sendwyre.com/" },
  { name: "Request Finance", category: "Payments", location: "United States", founded: 2017, desc: "Crypto invoicing and accounts payable platform for Web3 companies.", url: "https://www.request.finance/" },
  { name: "Transak", category: "Payments", location: "United States", founded: 2019, desc: "Global fiat-to-crypto payment gateway integrated into 300+ DeFi and NFT apps.", url: "https://transak.com/" },
  { name: "MoonPay", category: "Payments", location: "Miami, FL", founded: 2019, desc: "Leading crypto on-ramp enabling fiat purchases of 80+ crypto assets in 160+ countries.", url: "https://www.moonpay.com/" },
  { name: "Ramp Network", category: "Payments", location: "United States", founded: 2018, desc: "Fiat-to-crypto on-ramp infrastructure embedded in hundreds of Web3 applications.", url: "https://ramp.network/" },
  // Layer 1 & Layer 2
  { name: "Solana Labs", category: "Blockchain Infrastructure", location: "San Francisco, CA", founded: 2018, desc: "Builder of Solana, the high-performance L1 blockchain with 65,000 TPS capability.", url: "https://solanalabs.com/" },
  { name: "Optimism (OP Labs)", category: "Blockchain Infrastructure", location: "San Francisco, CA", founded: 2019, desc: "Ethereum Layer 2 scaling solution using optimistic rollups for fast, cheap transactions.", url: "https://www.optimism.io/" },
  { name: "Polygon", category: "Blockchain Infrastructure", location: "United States", founded: 2017, desc: "Leading Ethereum Layer 2 and sidechain scaling solution powering major Web3 apps.", url: "https://polygon.technology/" },
  { name: "Arbitrum (Offchain Labs)", category: "Blockchain Infrastructure", location: "New York, NY", founded: 2018, desc: "Ethereum Layer 2 using optimistic rollups, the largest L2 by TVL.", url: "https://arbitrum.io/" },
  { name: "Starkware", category: "Blockchain Infrastructure", location: "United States", founded: 2018, desc: "ZK-rollup technology company scaling Ethereum with zero-knowledge proofs.", url: "https://starkware.co/" },
  { name: "Celestia", category: "Blockchain Infrastructure", location: "United States", founded: 2019, desc: "Modular blockchain network enabling customizable rollup deployment.", url: "https://celestia.org/" },
  { name: "Sei Labs", category: "Blockchain Infrastructure", location: "San Francisco, CA", founded: 2022, desc: "High-performance Layer 1 blockchain optimized for trading applications.", url: "https://www.sei.io/" },
  { name: "Aptos Labs", category: "Blockchain Infrastructure", location: "Palo Alto, CA", founded: 2021, desc: "Layer 1 blockchain built by ex-Meta Diem engineers using Move programming language.", url: "https://aptoslabs.com/" },
  { name: "Mysten Labs (Sui)", category: "Blockchain Infrastructure", location: "Redwood City, CA", founded: 2021, desc: "Creator of Sui blockchain, a high-throughput L1 built on the Move language.", url: "https://mystenlabs.com/" },
  { name: "Hedera", category: "Blockchain Infrastructure", location: "Dallas, TX", founded: 2017, desc: "Enterprise-grade public ledger using hashgraph consensus, governed by 39 global companies.", url: "https://hedera.com/" },
  // Venture & Investment
  { name: "a16z Crypto (Andreessen Horowitz)", category: "Venture Capital", location: "Menlo Park, CA", founded: 2018, desc: "The world's largest crypto venture fund with $7.6B+ deployed in Web3 and blockchain.", url: "https://a16zcrypto.com/" },
  { name: "Multicoin Capital", category: "Venture Capital", location: "Austin, TX", founded: 2017, desc: "Thesis-driven crypto investment firm focused on open-source protocols and infrastructure.", url: "https://multicoin.capital/" },
  { name: "Pantera Capital", category: "Venture Capital", location: "Menlo Park, CA", founded: 2013, desc: "First US institutional investment firm focused exclusively on blockchain and digital assets.", url: "https://panteracapital.com/" },
  { name: "Dragonfly Capital", category: "Venture Capital", location: "San Francisco, CA", founded: 2018, desc: "Crypto-native venture fund investing globally in blockchain infrastructure and DeFi.", url: "https://www.dragonfly.xyz/" },
  { name: "Polychain Capital", category: "Venture Capital", location: "San Francisco, CA", founded: 2016, desc: "Early-stage crypto investment fund managing $1B+ backing protocols and Web3 companies.", url: "https://polychain.capital/" },
  // Identity & Security
  { name: "Civic Technologies", category: "Identity & Security", location: "San Francisco, CA", founded: 2015, desc: "Blockchain-based digital identity verification platform for decentralized apps.", url: "https://www.civic.com/" },
  { name: "Spruce Systems", category: "Identity & Security", location: "New York, NY", founded: 2020, desc: "Decentralized identity and verifiable credentials infrastructure for Web3.", url: "https://spruceid.com/" },
  { name: "Evernym", category: "Identity & Security", location: "Salt Lake City, UT", founded: 2013, desc: "Self-sovereign identity platform enabling portable digital credentials on the blockchain.", url: "https://www.evernym.com/" },
  { name: "Certik", category: "Identity & Security", location: "New York, NY", founded: 2018, desc: "Blockchain security company auditing smart contracts and ranking protocol security.", url: "https://www.certik.com/" },
  { name: "OpenZeppelin", category: "Identity & Security", location: "United States", founded: 2015, desc: "Security standards and auditing for Ethereum smart contracts and DeFi protocols.", url: "https://openzeppelin.com/" },
  // Data & Research
  { name: "Messari", category: "Analytics & Compliance", location: "New York, NY", founded: 2018, desc: "Crypto research and data platform used by institutions, funds, and regulators.", url: "https://messari.io/" },
  { name: "Nansen", category: "Analytics & Compliance", location: "United States", founded: 2020, desc: "On-chain analytics platform labeling wallets to track smart money and whale activity.", url: "https://www.nansen.ai/" },
  { name: "Dune Analytics", category: "Analytics & Compliance", location: "United States", founded: 2018, desc: "Community-powered blockchain data platform for creating and sharing on-chain dashboards.", url: "https://dune.com/" },
  { name: "Glassnode", category: "Analytics & Compliance", location: "United States", founded: 2018, desc: "On-chain market intelligence for Bitcoin, Ethereum, and DeFi ecosystem analytics.", url: "https://glassnode.com/" },
  { name: "Token Terminal", category: "Analytics & Compliance", location: "United States", founded: 2019, desc: "Financial metrics and fundamentals data platform for blockchain protocols.", url: "https://tokenterminal.com/" },
  // Other Notable
  { name: "Filecoin (Protocol Labs)", category: "Developer Tools", location: "San Francisco, CA", founded: 2014, desc: "Decentralized data storage network offering an open marketplace for cloud storage.", url: "https://filecoin.io/" },
  { name: "Helium Systems", category: "Blockchain Infrastructure", location: "San Francisco, CA", founded: 2013, desc: "Decentralized wireless network using blockchain token incentives for IoT coverage.", url: "https://www.helium.com/" },
  { name: "Render Network", category: "Developer Tools", location: "United States", founded: 2017, desc: "Decentralized GPU rendering network for 3D content, AI, and metaverse applications.", url: "https://rendernetwork.com/" },
  { name: "Chainlink Labs", category: "Blockchain Infrastructure", location: "San Francisco, CA", founded: 2017, desc: "Leading decentralized oracle network connecting smart contracts to real-world data.", url: "https://chain.link/" },
  { name: "Ava Labs (Avalanche)", category: "Blockchain Infrastructure", location: "New York, NY", founded: 2018, desc: "Creator of Avalanche, a high-speed, low-cost smart contract platform for DeFi.", url: "https://www.avalabs.org/" },
];

export const DIGITAL_CATEGORIES = [
  "All",
  "Exchange",
  "Blockchain Infrastructure",
  "DeFi",
  "NFT & Marketplace",
  "NFT & Gaming",
  "Custody & Banking",
  "Stablecoin & Payments",
  "Payments",
  "Developer Tools",
  "Analytics & Compliance",
  "Venture Capital",
  "Identity & Security",
  "Media & Data",
];