export const SHOP_CATEGORIES = [
  "All",
  "Clothing",
  "Accessories",
  "Home & Kitchen",
  "Outdoor & Sport",
  "Tools & Hardware",
  "Health & Beauty",
  "Food & Beverage",
  "Furniture",
];

export const SHOP_PRODUCTS = [
  // Clothing
  {
    id: 1,
    name: "Classic American Denim Jeans",
    brand: "All American Clothing Co.",
    category: "Clothing",
    price: "$79",
    location: "Arcanum, OH",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80",
    description: "100% American-made denim jeans, sewn by hand in Ohio. Built to last a lifetime.",
    url: "https://www.allamericanclothing.com/",
    verified: true,
    featured: true,
  },
  {
    id: 2,
    name: "Heritage Canvas Work Jacket",
    brand: "Filson",
    category: "Clothing",
    price: "$225",
    location: "Seattle, WA",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    description: "Heavy-duty canvas jacket built for decades of hard work. Made in the USA.",
    url: "https://www.filson.com/",
    verified: true,
    featured: false,
  },
  {
    id: 3,
    name: "Premium Blank Tee",
    brand: "US Blanks",
    category: "Clothing",
    price: "$28",
    location: "Los Angeles, CA",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    description: "Soft, durable blank tees cut and sewn in Los Angeles from USA-grown cotton.",
    url: "https://usblanks.net/",
    verified: true,
    featured: false,
  },
  // Accessories
  {
    id: 4,
    name: "Handcrafted Leather Wallet",
    brand: "Tanner Goods",
    category: "Accessories",
    price: "$85",
    location: "Portland, OR",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
    description: "Slim minimalist wallet hand-stitched from full-grain American leather in Portland.",
    url: "https://www.tannergoods.com/",
    verified: true,
    featured: true,
  },
  {
    id: 5,
    name: "Duluth Canvas Pack",
    brand: "Duluth Pack",
    category: "Accessories",
    price: "$189",
    location: "Duluth, MN",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    description: "Handcrafted canvas and leather pack built in Minnesota. A tradition since 1882.",
    url: "https://www.duluthpack.com/",
    verified: true,
    featured: false,
  },
  {
    id: 6,
    name: "Vermont Leather Gloves",
    brand: "Vermont Glove",
    category: "Accessories",
    price: "$65",
    location: "Vermont",
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=600&q=80",
    description: "Quality leather gloves crafted in Vermont by skilled artisans since 1920.",
    url: "https://vermontglove.com/",
    verified: true,
    featured: false,
  },
  // Home & Kitchen
  {
    id: 7,
    name: "Cast Iron Skillet",
    brand: "Lodge Cast Iron",
    category: "Home & Kitchen",
    price: "$45",
    location: "South Pittsburg, TN",
    image: "https://images.unsplash.com/photo-1588540304702-9d03dee9e70e?w=600&q=80",
    description: "America's oldest cast iron manufacturer since 1896. Pre-seasoned and ready to cook.",
    url: "https://www.lodgecastiron.com/",
    verified: true,
    featured: true,
  },
  {
    id: 8,
    name: "Stainless Steel Cookware Set",
    brand: "All-Clad",
    category: "Home & Kitchen",
    price: "$699",
    location: "Canonsburg, PA",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    description: "Professional-grade stainless steel cookware crafted in Pennsylvania for over 50 years.",
    url: "https://www.all-clad.com/",
    verified: true,
    featured: false,
  },
  {
    id: 9,
    name: "Vitamix Blender",
    brand: "Vitamix",
    category: "Home & Kitchen",
    price: "$449",
    location: "Olmsted Township, OH",
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&q=80",
    description: "World-class blenders made in Ohio for over 80 years. Engineered to last a lifetime.",
    url: "https://www.vitamix.com/",
    verified: true,
    featured: false,
  },
  {
    id: 10,
    name: "Nordic Bundt Pan",
    brand: "Nordicware",
    category: "Home & Kitchen",
    price: "$39",
    location: "Minneapolis, MN",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80",
    description: "Iconic bakeware made in Minneapolis since 1946. The original Bundt pan.",
    url: "https://www.nordicware.com/",
    verified: true,
    featured: false,
  },
  // Outdoor & Sport
  {
    id: 11,
    name: "GORUCK Rucksack",
    brand: "GORUCK",
    category: "Outdoor & Sport",
    price: "$395",
    location: "Jacksonville, FL",
    image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&q=80",
    description: "Military-grade rucksacks designed by Special Forces. Built to outlast everything.",
    url: "https://www.goruck.com/",
    verified: true,
    featured: true,
  },
  {
    id: 12,
    name: "Hardwood Desk Organizer",
    brand: "Grovemade",
    category: "Home & Kitchen",
    price: "$120",
    location: "Portland, OR",
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",
    description: "Beautifully crafted solid wood desk accessories, handmade in Portland, Oregon.",
    url: "https://grovemade.com/",
    verified: true,
    featured: false,
  },
  // Furniture
  {
    id: 13,
    name: "Modern Sofa",
    brand: "Maiden Home",
    category: "Furniture",
    price: "$2,199",
    location: "North Carolina",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    description: "Custom sofas crafted by North Carolina artisans using sustainably sourced hardwoods.",
    url: "https://maidenhome.com/",
    verified: true,
    featured: false,
  },
  // Health & Beauty
  {
    id: 14,
    name: "Artisan Perfume",
    brand: "Clue Perfumery",
    category: "Health & Beauty",
    price: "$95",
    location: "Chicago, IL",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80",
    description: "Independent perfumery formulating everything in-house in Chicago since 2023.",
    url: "https://www.clueperfumery.com/",
    verified: true,
    featured: false,
  },
  // Tools & Hardware
  {
    id: 15,
    name: "Flatware Set",
    brand: "Liberty Tabletop",
    category: "Tools & Hardware",
    price: "$149",
    location: "Sherrill, NY",
    image: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&q=80",
    description: "The only flatware still made in the USA, crafted in Sherrill, New York.",
    url: "https://www.libertytabletop.com/",
    verified: true,
    featured: false,
  },
];